version: '3.4'
services:

  rasa-server:
    image: rasa/rasa:3.0.6-full
    working_dir: /app
    build: "./"
    restart: always
    volumes:
    - ./actions:/app/actions
    - ./data:/app/data
    # command: "rasa run --enable-api --cors \"*\" --debug"
    ports:
    - '5006:5005'
    networks:
    - all

  rasa-actions-server:
    image: rasa/rasa-sdk:3.0.4
    working_dir: /app
    build: "./"
    restart: always
    volumes:
    - ./actions:/app/actions
    - ./utils:/app/utils
    # command: ["rasa", "run", "actions"]
    ports:
    - '5055:5055'
    networks:
    - all

networks:
  all:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"